theme: minima
title: J.M. Speight Esq
author: Martin Speight
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Something about topological solitons

# social links
github_username:  cp1lump # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
